language: node_js
node_js:
  - '11'
  - '10'
  - '8'

services:
  - postgresql

addons:
  postgresql: '9.6'

before_script:
  - psql -c 'CREATE DATABASE shyft_tests;' -U postgres

after_success:
  - npm run coverage-ci
