language: node_js
node_js:
  - '11'
  - '10'
  - '8'

services:
  - postgresql

addons:
  postgresql: '9.6'

before_script:
  - psql -c 'CREATE DATABASE shyft_tests;' -U postgres

script:
  - npm run lint &&
    npm run coverage-ci

before_deploy:
  - npm run clean &&
    npm run build

deploy:
  skip_cleanup: true
  provider: npm
  email: christian.kalmar@gmail.com
  api_key:
    secure: B2ajALyHpaiTpsfvHXjSnXjokpCR04ENdqkAE4T+m9ULwG6BfHqn3dL09rbJDGgdD+x4QEhXkWQcf1ZrhoHSrnr6eW5FYpC3rwGCLHEn7HVjIvPKlfsiKIcVqiXa61T1G9FYK9ARXnTw2h4rEgWTYP09M3Q3Kz/lLnvRr2yer2c4xd234bD7kO/2RX+g8n93RItHaf/iutaj7gH91gFQg6+/lj/f3JqyxTuG5ZTcrpCTpm1EF34qDESt95j2b/yAXfPpNdvwYUC/Z6PjA5yhn/4BM/f3Mt4a3zdJhbcRJ34e9MvRFyi9elFTl1yakp2HPxbW2ZzQu7Eksj3HljQ58DMR1yU7I50pYA8VdBfKZjaA0wapSkP7CwTmMxbksHj9uxAT8EPh43gPiy0/r0sMvdAWDea8s7GvWVC5AJGzXnv+R1Y6+/8V1POdBperUG32+SDLBlUfxzggt13jE7sUcIqrjxxTVuKxoMjC2Lm2ngdTDmRLRFvr5wWRQ5tk3NjXIxT9us/a4dhcs1weCGzpdQTN8Cku/SWjVx/wM0mEKSLSq1dKjfSgCFW+1kFN14ZHl4grClh0zpEkP63PO+1N28b7t2PGIHuhh5fzSkkPUpfhvPgV9oyvBFWLGboF55wCLjoJnh1u+ZALYVnPw0WC44QJC3cmD86AdSABJPoFBqA=
  on:
    tags: true
    repo: chriskalmar/shyft-storage-connector
