language: node_js
node_js:
  - '11'
  - '10'
  - '8'

services:
  - postgresql

addons:
  postgresql: '9.6'

before_script:
  - psql -c 'CREATE DATABASE shyft_tests;' -U postgres

script:
  - npm run lint &&
    npm run coverage-ci

before_deploy:
  - npm run clean &&
    npm run build

deploy:
  provider: npm
  email: christian.kalmar@gmail.com
  api_key:
    secure: kwrGiQ+BqwL8tu6snDkW0UOrdes9Iki3tZHHejkSf42IDxF+rc5E9/t6T9nHK5BT0Pvbp8ydXVENsZJYG4XOwDBdX8ysTVHW7Vs6OMgGlo6XAhJgdldPB0u34KPFaHV4yGVuNazgfM0qCnHcyiEKWyv3Art8EOkSpuKCXFmFoEczuQpbFvlAMyPBWBJ+NDKG9AeqyzTlWvbcqqqWXs8pD0OFl+NmYOoSVKTBbPz8GlGjHVZcWzlJdmPM++6EuffwLB+QAg28GGYqv23yz+LtWyjUtoqEMoZfd3T7DAXaQCsrDsrSlyh8+YeALIZTd2kYVz5+uiYszqwRrATDaXAC7NNIHa0vIQCP+6rkP7uoZwaqApSztGor4gzaqJyKcjyLg6lcr40zW5RcMlZcsH/VipEez2+Fj92Rp69fhiyasjE1HrXKo0Qwo+8Pjfeoq4MBgwZ0xyEMW2eVHf+78rxYN6Fn56VHgrrpEQed2gJ6c+LCZNu4ABRXI9w++k/DifFzR6YPvjJHZrrYv9xrPcP1Kst60H6aNMngijNqxvWlSzefQ+mMvp305Qo5INv6KhumhAqju/tNMunq0BGthildrP+kXNkyoEh8NXz3ul0aAWEG8sU4bToN9+zGwyJZSnZpaKQgAFnETDU58NGwk9F+wawoxFMASv0otL1uJWGeCzs=
  on:
    tags: true
    repo: chriskalmar/shyft-storage-connector
