language: node_js
node_js:
  - '14'
  - '12'
  - '10'

services:
  - postgresql

addons:
  postgresql: '9.6'

before_script:
  - psql -c 'CREATE DATABASE shyft_tests;' -U postgres

script:
  - npm run lint &&
    npm run coverage-ci

before_deploy:
  - npm run clean &&
    npm run build

deploy:
  skip_cleanup: true
  provider: npm
  email: christian.kalmar@gmail.com
  api_key:
    secure: iDYKFuQYk65e+QPrh9JBtGhwqQTnWTsxrMLCV6y/d//LLh4UoSdf1EASrPQU1I2nF7FIAIdRjQLRy8lZR3mZJanNB6tNqvzoZmLMo3vxLpigzVSdoJ6UInpEW6RSJjhwqt8IKjBrf0tBMXA86H/EgQdNeh5Q0hvMvBlcVjeRN/WuO9Wj1b2h346FepkE0cRGvpDYUy12RGmNcfMll5EYR7lzxhXrov6tpbRrAbzSzEObIJL9kYaMq4m12z3wkjxPljMULJvnCybqxMpyBvb7l6QZVYMscW4yMWyyK5PXfn3uqMB6PJQnZW3zlyDk8LUPXe4J4hB4HzYM/2DsFxoB3w0StKI+8NjzMPE2qnIdSdKuX5JjDF/BQroIogCdiBNJROwCvs96FoV+xL9CxrITfd+RCfogqgjAhgw+/iw6GyA8mfbHJ2gJ0nDmsaqkA1UVjHyZVxvs6ZC/xUMblga+vtuLbnczP8MjPoVSIO7EUlyx5KAEXW1cSg4oFUHmDMEDQ65QmEi7Mv2jbj0cUEd4PkYxTG/y7VH4yDVAuB8QrLqD+pybPAUM0uVgdUp4W+lxW52xF0fsv1yoBa6/Si8AfCFYo5ml6phLX5L0XNODQkvzFY8jps9CCfPRmyLnLDanEvgAeinRLDsQUsOdKbtrkgBE3OsuhIAJS0SQsFYNfLc=
  on:
    tags: true
    repo: chriskalmar/shyft-storage-connector
    node: '12'
