codecov:
  strict_yaml_branch: master  # only use the latest copy on master branch
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"


  # notify:
  #   slack:
  #     default:                        # -> see "sections" below
  #       url: "https://hooks.slack.com/..."  #*S unique Slack notifications url
  #       branches: null                # -> see "branch patterns" below
  #       threshold: null               # -> see "threshold" below
  #       attachments: "sunburst, diff" # list of attachments to include in notification
  #       message: "template string"    # [advanced] -> see "customized message" below


  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
